# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Climate Monitoring
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_core.tasks.transformation import (
    extract_column_as_type as extract_column_as_type,
)
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import create_docx as create_docx
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_subjectgroup_observations as get_subjectgroup_observations,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_line_chart as draw_line_chart,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)

# %% [markdown]
# ## Set Workflow Details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Time Range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .partial(time_format="%d %b %Y %H:%M:%S %Z", **time_range_params)
    .call()
)


# %% [markdown]
# ## Extract Timezone Selection

# %%
# parameters

get_timezone_params = dict()

# %%
# call the task


get_timezone = (
    get_timezone_from_time_range.set_task_instance_id("get_timezone")
    .handle_errors()
    .with_tracing()
    .partial(time_range=time_range, **get_timezone_params)
    .call()
)


# %% [markdown]
# ## Select EarthRanger Data Source

# %%
# parameters

er_client_name_params = dict(
    data_source=...,
)

# %%
# call the task


er_client_name = (
    set_er_connection.set_task_instance_id("er_client_name")
    .handle_errors()
    .with_tracing()
    .partial(**er_client_name_params)
    .call()
)


# %% [markdown]
# ## Get Subject Group Observations from EarthRanger

# %%
# parameters

subject_obs_params = dict(
    subject_group_name=...,
)

# %%
# call the task


subject_obs = (
    get_subjectgroup_observations.set_task_instance_id("subject_obs")
    .handle_errors()
    .with_tracing()
    .partial(
        client=er_client_name,
        time_range=time_range,
        raise_on_empty=True,
        include_details=True,
        include_subjectsource_details=True,
        filter="none",
        **subject_obs_params,
    )
    .call()
)


# %% [markdown]
# ## Remove Extra Column Prefix

# %%
# parameters

drop_extra_prefix_params = dict()

# %%
# call the task


drop_extra_prefix = (
    drop_column_prefix.set_task_instance_id("drop_extra_prefix")
    .handle_errors()
    .with_tracing()
    .partial(
        df=subject_obs,
        prefix="extra__",
        duplicate_strategy="suffix",
        **drop_extra_prefix_params,
    )
    .call()
)


# %% [markdown]
# ## Preprocess Columns

# %%
# parameters

process_columns_params = dict()

# %%
# call the task


process_columns = (
    map_columns.set_task_instance_id("process_columns")
    .handle_errors()
    .with_tracing()
    .partial(
        df=drop_extra_prefix,
        drop_columns=[],
        retain_columns=[
            "id",
            "subject_id",
            "created_at",
            "recorded_at",
            "source",
            "device_status_properties",
            "observation_details",
            "geometry",
            "subject__name",
        ],
        rename_columns={"subject__name": "weather_station"},
        **process_columns_params,
    )
    .call()
)


# %% [markdown]
# ## Convert to timezone

# %%
# parameters

convert_to_user_timezone_params = dict()

# %%
# call the task


convert_to_user_timezone = (
    convert_values_to_timezone.set_task_instance_id("convert_to_user_timezone")
    .handle_errors()
    .with_tracing()
    .partial(
        df=process_columns,
        timezone=get_timezone,
        columns=["time"],
        **convert_to_user_timezone_params,
    )
    .call()
)


# %% [markdown]
# ## Normalize Observation Details

# %%
# parameters

normalize_obs_details_params = dict()

# %%
# call the task


normalize_obs_details = (
    normalize_json_column.set_task_instance_id("normalize_obs_details")
    .handle_errors()
    .with_tracing()
    .partial(
        df=convert_to_user_timezone,
        column="observation_details",
        skip_if_not_exists=False,
        sort_columns=True,
        **normalize_obs_details_params,
    )
    .call()
)


# %% [markdown]
# ## Remove Column Prefix Observation Details

# %%
# parameters

drop_obs_details_prefix_params = dict()

# %%
# call the task


drop_obs_details_prefix = (
    drop_column_prefix.set_task_instance_id("drop_obs_details_prefix")
    .handle_errors()
    .with_tracing()
    .partial(
        df=normalize_obs_details,
        prefix="observation_details__",
        duplicate_strategy="suffix",
        **drop_obs_details_prefix_params,
    )
    .call()
)


# %% [markdown]
# ## Extract Date

# %%
# parameters

extract_date_params = dict()

# %%
# call the task


extract_date = (
    extract_column_as_type.set_task_instance_id("extract_date")
    .handle_errors()
    .with_tracing()
    .partial(
        df=drop_obs_details_prefix,
        column_name="recorded_at",
        output_type="date",
        output_column_name="date",
        **extract_date_params,
    )
    .call()
)


# %% [markdown]
# ## Select Weather Stations

# %%
# parameters

filtered_weather_station_params = dict(
    values=...,
)

# %%
# call the task


filtered_weather_station = (
    filter_row_values.set_task_instance_id("filtered_weather_station")
    .handle_errors()
    .with_tracing()
    .partial(
        df=extract_date, column="weather_station", **filtered_weather_station_params
    )
    .call()
)


# %% [markdown]
# ## Set Groupers

# %%
# parameters

groupers_params = dict(
    groupers=...,
)

# %%
# call the task


groupers = (
    set_groupers.set_task_instance_id("groupers")
    .handle_errors()
    .with_tracing()
    .partial(**groupers_params)
    .call()
)


# %% [markdown]
# ## Add temporal index

# %%
# parameters

df_with_temporal_index_params = dict()

# %%
# call the task


df_with_temporal_index = (
    add_temporal_index.set_task_instance_id("df_with_temporal_index")
    .handle_errors()
    .with_tracing()
    .partial(
        df=filtered_weather_station,
        time_col="recorded_at",
        groupers=groupers,
        cast_to_datetime=True,
        format="mixed",
        **df_with_temporal_index_params,
    )
    .call()
)


# %% [markdown]
# ## Split by Group

# %%
# parameters

split_weather_groups_params = dict()

# %%
# call the task


split_weather_groups = (
    split_groups.set_task_instance_id("split_weather_groups")
    .handle_errors()
    .with_tracing()
    .partial(
        df=df_with_temporal_index, groupers=groupers, **split_weather_groups_params
    )
    .call()
)


# %% [markdown]
# ## Persist Observations

# %%
# parameters

persist_observations_params = dict(
    filename=...,
    filetypes=...,
    filename_prefix=...,
)

# %%
# call the task


persist_observations = (
    persist_df_wrapper.set_task_instance_id("persist_observations")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        sanitize=True,
        **persist_observations_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_weather_groups)
)


# %% [markdown]
# ## Calculate Daily Summary

# %%
# parameters

daily_weather_params = dict()

# %%
# call the task


daily_weather = (
    summarize_df.set_task_instance_id("daily_weather")
    .handle_errors()
    .with_tracing()
    .partial(
        groupby_cols=["weather_station", "date"],
        summary_params=[
            {
                "display_name": "daily_precipitation",
                "aggregator": "sum",
                "column": "precipitation",
            },
            {
                "display_name": "daily_temperature",
                "aggregator": "mean",
                "column": "surface_air_temperature",
            },
        ],
        reset_index=True,
        **daily_weather_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_weather_groups)
)


# %% [markdown]
# ## Persist Daily Summary

# %%
# parameters

persist_daily_summary_params = dict(
    filename=...,
    filename_prefix=...,
)

# %%
# call the task


persist_daily_summary = (
    persist_df_wrapper.set_task_instance_id("persist_daily_summary")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetypes=["csv"],
        sanitize=False,
        **persist_daily_summary_params,
    )
    .mapvalues(argnames=["df"], argvalues=daily_weather)
)


# %% [markdown]
# ## Draw Precipitation Chart

# %%
# parameters

precipitation_chart_params = dict(
    widget_id=...,
)

# %%
# call the task


precipitation_chart = (
    draw_line_chart.set_task_instance_id("precipitation_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        x_column="date",
        y_column="daily_precipitation",
        category_column="weather_station",
        line_kwargs={"shape": "spline"},
        layout_kwargs={
            "xaxis": {"title": "Date"},
            "yaxis": {"title": "Precipitation (mm)"},
            "legend_title": "Weather Station",
            "hovermode": "closest",
        },
        smoothing={"method": "spline", "y_min": 0},
        **precipitation_chart_params,
    )
    .mapvalues(argnames=["dataframe"], argvalues=daily_weather)
)


# %% [markdown]
# ## Persist Precipitation Chart as Text

# %%
# parameters

persist_precipitation_params = dict(
    filename=...,
    filename_suffix=...,
)

# %%
# call the task


persist_precipitation = (
    persist_text.set_task_instance_id("persist_precipitation")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_precipitation_params,
    )
    .mapvalues(argnames=["text"], argvalues=precipitation_chart)
)


# %% [markdown]
# ## Create Precipitation Widget

# %%
# parameters

precipitation_chart_widget_params = dict()

# %%
# call the task


precipitation_chart_widget = (
    create_plot_widget_single_view.set_task_instance_id("precipitation_chart_widget")
    .handle_errors()
    .with_tracing()
    .partial(
        title="Daily Precipitation by Station", **precipitation_chart_widget_params
    )
    .map(argnames=["view", "data"], argvalues=persist_precipitation)
)


# %% [markdown]
# ## Merge Precipitation Widget Views

# %%
# parameters

grouped_precipitation_widget_params = dict()

# %%
# call the task


grouped_precipitation_widget = (
    merge_widget_views.set_task_instance_id("grouped_precipitation_widget")
    .handle_errors()
    .with_tracing()
    .partial(widgets=precipitation_chart_widget, **grouped_precipitation_widget_params)
    .call()
)


# %% [markdown]
# ## Draw Temperature Chart

# %%
# parameters

temperature_chart_params = dict(
    smoothing=...,
    widget_id=...,
)

# %%
# call the task


temperature_chart = (
    draw_line_chart.set_task_instance_id("temperature_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        x_column="date",
        y_column="daily_temperature",
        category_column="weather_station",
        line_kwargs={"shape": "spline"},
        layout_kwargs={
            "xaxis": {"title": "Date"},
            "yaxis": {"title": "Average Daily Temperature (Celsius)"},
            "legend_title": "Weather Station",
            "hovermode": "closest",
        },
        **temperature_chart_params,
    )
    .mapvalues(argnames=["dataframe"], argvalues=daily_weather)
)


# %% [markdown]
# ## Persist Temperature Chart as Text

# %%
# parameters

persist_temperature_params = dict(
    filename=...,
    filename_suffix=...,
)

# %%
# call the task


persist_temperature = (
    persist_text.set_task_instance_id("persist_temperature")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"], **persist_temperature_params
    )
    .mapvalues(argnames=["text"], argvalues=temperature_chart)
)


# %% [markdown]
# ## Create Temperature Widget

# %%
# parameters

temperature_chart_widget_params = dict()

# %%
# call the task


temperature_chart_widget = (
    create_plot_widget_single_view.set_task_instance_id("temperature_chart_widget")
    .handle_errors()
    .with_tracing()
    .partial(title="Daily Temperature by Station", **temperature_chart_widget_params)
    .map(argnames=["view", "data"], argvalues=persist_temperature)
)


# %% [markdown]
# ## Merge Temperature Widget Views

# %%
# parameters

grouped_temperature_widget_params = dict()

# %%
# call the task


grouped_temperature_widget = (
    merge_widget_views.set_task_instance_id("grouped_temperature_widget")
    .handle_errors()
    .with_tracing()
    .partial(widgets=temperature_chart_widget, **grouped_temperature_widget_params)
    .call()
)


# %% [markdown]
# ## Create Climate Report

# %%
# parameters

create_climate_report_params = dict(
    template_path=...,
)

# %%
# call the task


create_climate_report = (
    create_docx.set_task_instance_id("create_climate_report")
    .handle_errors()
    .with_tracing()
    .partial(
        context={
            "items": [
                {
                    "item_type": "text",
                    "key": "title",
                    "value": "Climate Monitoring Report",
                },
                {"item_type": "timerange", "key": "report_date", "value": time_range},
                {
                    "item_type": "image",
                    "key": "temperature_chart",
                    "value": persist_temperature,
                    "screenshot_config": {"wait_for_timeout": 0},
                },
                {
                    "item_type": "image",
                    "key": "precipitation_chart",
                    "value": persist_precipitation,
                    "screenshot_config": {"wait_for_timeout": 0},
                },
                {"item_type": "table", "key": "summary", "value": daily_weather},
            ]
        },
        groupers=groupers,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_prefix="climate_report",
        **create_climate_report_params,
    )
    .call()
)


# %% [markdown]
# ## Create A Climate Dashboard

# %%
# parameters

climate_dashboard_params = dict(
    warning=...,
)

# %%
# call the task


climate_dashboard = (
    gather_dashboard.set_task_instance_id("climate_dashboard")
    .handle_errors()
    .with_tracing()
    .partial(
        details=workflow_details,
        widgets=[grouped_precipitation_widget, grouped_temperature_widget],
        time_range=time_range,
        groupers=groupers,
        **climate_dashboard_params,
    )
    .call()
)
