# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, RootModel


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: str | None = Field("", title="Workflow Description")


class SubjectObs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    subject_group_name: str = Field(
        ...,
        description="⚠️ The use of a group with mixed subtypes could lead to unexpected results",
        title="Subject Group Name",
    )


class FilteredWeatherStation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    values: list[str] | None = Field(
        None,
        description="Select the interested weather stations by subject names. If None, all weather stations in the subject group will be included. Note that we will always download all observations in the subject group before filtering.",
        title="Weather Station",
    )


class Filetype(str, Enum):
    csv = "csv"
    gpkg = "gpkg"
    geoparquet = "geoparquet"


class PersistObservations(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filetypes: list[Filetype] | None = Field(
        ["csv"], description="The output format", title="Filetypes"
    )
    filename_prefix: str | None = Field(
        "observations",
        description="            Optional filename prefix to persist text to within the `root_path`.\n            We will always add a suffix based on the dataframe content hash to avoid duplicates.\n            ",
        title="Filename Prefix",
    )


class PersistDailySummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filename_prefix: str | None = Field(
        "daily_summary",
        description="            Optional filename prefix to persist text to within the `root_path`.\n            We will always add a suffix based on the dataframe content hash to avoid duplicates.\n            ",
        title="Filename Prefix",
    )


class CreateClimateReport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    template_path: str = Field(
        ...,
        description="Path or URL to the Word template (.docx) file with Jinja2 placeholders. Supports local paths and remote URLs (http://, https://).",
        title="Template Path",
    )


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class SpatialGrouper(RootModel[str]):
    root: str = Field(..., title="Spatial Regions")


class TemporalGrouper(str, Enum):
    field_Y = "%Y"
    field_B = "%B"
    field_Y__m = "%Y-%m"
    field_j = "%j"
    field_d = "%d"
    field_A = "%A"
    field_H = "%H"
    field_Y__m__d = "%Y-%m-%d"


class ValueGrouper(str, Enum):
    weather_station = "weather_station"


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: TimezoneInfo | None = Field(None, title="Timezone")


class ErClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class Groupers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    groupers: list[ValueGrouper | TemporalGrouper | SpatialGrouper] | None = Field(
        None,
        description="            Specify how the data should be grouped to create the views for your dashboard.\n            This field is optional; if left blank, all the data will appear in a single view.\n            ",
        title=" ",
    )


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: WorkflowDetails | None = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set Workflow Details",
    )
    time_range: TimeRange | None = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    er_client_name: ErClientName | None = Field(
        None, title="Select EarthRanger Data Source"
    )
    subject_obs: SubjectObs | None = Field(
        None, title="Get Subject Group Observations from EarthRanger"
    )
    filtered_weather_station: FilteredWeatherStation | None = Field(
        None, title="Select Weather Stations"
    )
    groupers: Groupers | None = Field(None, title="Set Groupers")
    persist_observations: PersistObservations | None = Field(
        None, title="Persist Observations"
    )
    persist_daily_summary: PersistDailySummary | None = Field(
        None, title="Persist Daily Summary"
    )
    create_climate_report: CreateClimateReport | None = Field(
        None, title="Create Climate Report"
    )
