# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from typing import List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class SubjectObs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    subject_group_name: str = Field(
        ...,
        description="⚠️ The use of a group with mixed subtypes could lead to unexpected results",
        title="Subject Group Name",
    )


class FilteredWeatherStation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    values: Optional[List[str]] = Field(
        None,
        description="The values to keep. If None, no filtering is applied.",
        title="Values",
    )


class PersistObservations(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filename_prefix: Optional[str] = Field(
        None,
        description="            Optional filename prefix to persist text to within the `root_path`.\n            We will always add a suffix based on the dataframe content hash to avoid duplicates.\n            ",
        title="Filename Prefix",
    )


class PersistDailySummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filename_prefix: Optional[str] = Field(
        None,
        description="            Optional filename prefix to persist text to within the `root_path`.\n            We will always add a suffix based on the dataframe content hash to avoid duplicates.\n            ",
        title="Filename Prefix",
    )


class DrawSummaryTable(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    columns: Optional[List[str]] = Field(
        None,
        description="The list of dataframe columns to render in the table. Leave empty to render all columns",
        title="Columns",
    )


class CreateClimateReport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    template_path: str = Field(
        ...,
        description="Path or URL to the Word template (.docx) file with Jinja2 placeholders. Supports local paths and remote URLs (http://, https://).",
        title="Template Path",
    )


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class SpatialGrouper(BaseModel):
    spatial_index_name: str = Field(..., title="Spatial Regions")


class TemporalGrouper(BaseModel):
    temporal_index: str = Field(..., title="Time")


class ValueGrouper(BaseModel):
    index_name: str = Field(..., title="Category")


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")


class ErClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class Groupers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    groupers: Optional[List[Union[ValueGrouper, TemporalGrouper, SpatialGrouper]]] = (
        Field(
            None,
            description="            Specify how the data should be grouped to create the views for your dashboard.\n            This field is optional; if left blank, all the data will appear in a single view.\n            ",
            title=" ",
        )
    )


class Params(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set Workflow Details",
    )
    time_range: Optional[TimeRange] = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    er_client_name: Optional[ErClientName] = Field(
        None, title="Select EarthRanger Data Source"
    )
    subject_obs: Optional[SubjectObs] = Field(
        None, title="Get Subject Group Observations from EarthRanger"
    )
    filtered_weather_station: Optional[FilteredWeatherStation] = Field(
        None, title="Select Weather Stations"
    )
    groupers: Optional[Groupers] = Field(None, title="Set Groupers")
    persist_observations: Optional[PersistObservations] = Field(
        None, title="Persist Observations"
    )
    persist_daily_summary: Optional[PersistDailySummary] = Field(
        None, title="Persist Daily Summary"
    )
    draw_summary_table: Optional[DrawSummaryTable] = Field(
        None, title="Draw Summary Table"
    )
    create_climate_report: Optional[CreateClimateReport] = Field(
        None, title="Create Climate Report"
    )
